#! /usr/bin/sh

echo
echo "GETTING with query existent..."
curl -i -H "Content-Type: application/json" -X GET  http://localhost:9876/api/notes?query=milk

echo
echo "GETTING with query non existent..."
curl -i -H "Content-Type: application/json" -X GET  http://localhost:9876/api/notes?query="goatmilk+milk"

echo
echo "DONE GET..."
