#! /usr/bin/sh

echo
echo "GETING ALL.....!!!"
curl -i -H "Content-Type: application/json" -X GET  http://localhost:8080/api/notes/


echo
echo "GETTING note 3..."
curl -i -H "Content-Type: application/json" -X GET  http://localhost:8080/api/notes/3

echo
echo "GETTING note 12..."
curl -i -H "Content-Type: application/json" -X GET  http://localhost:8080/api/notes/12


echo
echo "DONE GET..."
